wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    session_history: code/_session_history.ipynb
    start_time: 1634984617
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      - 13
      4: 3.8.8
      5: 0.12.5
      8:
      - 1
      - 5
